-- 由 sys_module.csv / sys_module_field.csv / sys_table_relation.csv 自动生成，不要手改。
-- 这三张表本身就是元数据配置库（config库）的内容，school.sql 那些才是业务数据（school库）。

INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (101, 'MOD-SCHOOL-STUDENT', '学生列表', 'student', 0);
INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (102, 'MOD-SCHOOL-COURSE', '课程排课中心', 'course', 0);
INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (103, 'MOD-STUDENT-DETAIL', '学生核心基本档案', 'student', 101);
INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (104, 'MOD-STUDENT-AWARD', '学生荣誉管理', 'student_award', 101);
INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (105, 'MOD-STUDENT-COURSE', '选课与成绩管理', 'student_course', 101);
INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (106, 'MOD-STUDENT-AWARD-DETAIL', '荣誉材料与佐证明细', 'student_award_detail', 104);
INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (107, 'MOD-COURSE-SCHEDULE', '课程排课日程', 'course_schedule', 102);
INSERT INTO sys_module (id, module_code, module_name, primary_table, parent_id) VALUES (108, 'MOD-STUDENT-COURSE-SCORE', '选课考核成绩分项', 'student_course_score_item', 105);

INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (1, 101, 'student', 'id', '学生ID', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (2, 101, 'student', 'student_no', '学号', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (3, 101, 'student', 'name', '姓名', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (4, 101, 'student', 'clazz_id', '班级ID', 4);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (5, 101, 'student', 'status', '学籍状态', 5);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (15, 102, 'course', 'id', '课程ID', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (16, 102, 'course', 'course_code', '课程编码', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (17, 102, 'course', 'course_name', '课程名称', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (18, 102, 'course', 'credit', '学分', 4);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (19, 102, 'course', 'teacher_id', '教师ID', 5);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (20, 102, 'course', 'status', '开课状态', 6);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (21, 102, 'teacher', 'teacher_name', '主讲教师', 7);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (22, 102, 'teacher', 'title', '职称', 8);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (23, 102, 'course_syllabus', 'prerequisite', '先修要求', 9);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (24, 102, 'course_syllabus', 'syllabus_content', '教学大纲', 10);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (25, 107, 'course_schedule', 'day_of_week', '星期', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (26, 107, 'course_schedule', 'time_slot', '节次', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (27, 107, 'course_schedule', 'classroom', '上课教室', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (28, 105, 'student_course', 'id', '选课ID', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (29, 105, 'student_course', 'student_id', '学生ID', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (30, 105, 'student_course', 'course_id', '课程ID', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (31, 105, 'student_course', 'semester', '学期', 4);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (32, 105, 'student_course', 'course_name', '课程名称', 5);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (33, 105, 'student_course', 'score', '考核成绩', 6);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (37, 104, 'student_award', 'id', '荣誉ID', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (38, 104, 'student_award', 'student_id', '学生ID', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (39, 104, 'student_award', 'award_name', '荣誉名称', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (40, 104, 'student_award', 'award_date', '获奖日期', 4);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (43, 103, 'student', 'id', '学生ID', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (44, 103, 'student', 'student_no', '学号', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (45, 103, 'student', 'name', '学生姓名', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (46, 103, 'student', 'clazz_id', '班级ID', 4);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (47, 103, 'student', 'status', '学籍状态', 5);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (48, 103, 'clazz', 'id', '班级ID', 6);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (49, 103, 'clazz', 'clazz_name', '班级名称', 7);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (50, 103, 'clazz', 'grade', '所属年级', 8);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (51, 103, 'student_profile', 'id', '档案ID', 9);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (52, 103, 'student_profile', 'student_id', '学生外键ID', 10);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (53, 103, 'student_profile', 'id_card', '身份证号', 11);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (54, 103, 'student_profile', 'emergency_phone', '紧急联系电话', 12);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (56, 104, 'student_award', 'level', '荣誉级别', 5);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (57, 108, 'student_course_score_item', 'id', '分项ID', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (58, 108, 'student_course_score_item', 'student_course_id', '选课ID', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (59, 108, 'student_course_score_item', 'item_name', '考核分项名称', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (60, 108, 'student_course_score_item', 'weight', '权重占比', 4);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (61, 108, 'student_course_score_item', 'score', '分项得分', 5);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (62, 108, 'student_course_score_item', 'remark', '评语备注', 6);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (74, 106, 'student_award_detail', 'id', '材料ID', 1);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (75, 106, 'student_award_detail', 'award_id', '荣誉ID', 2);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (76, 106, 'student_award_detail', 'evidence_name', '材料名称', 3);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (77, 106, 'student_award_detail', 'evidence_no', '证书编号', 4);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (78, 106, 'student_award_detail', 'issuing_authority', '发证单位', 5);
INSERT INTO sys_module_field (id, module_id, table_name, column_name, display_name, sort_order) VALUES (79, 106, 'student_award_detail', 'award_score', '评优加分', 6);

INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (1, 'clazz', 'id', 'student', 'clazz_id', '1:N');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (2, 'student', 'id', 'student_profile', 'student_id', '1:1');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (3, 'student', 'id', 'student_course', 'student_id', '1:N');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (4, 'student', 'id', 'student_award', 'student_id', '1:N');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (5, 'student_course', 'id', 'student_course_score_item', 'student_course_id', '1:N');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (6, 'teacher', 'id', 'course', 'teacher_id', '1:N');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (7, 'course', 'id', 'course_syllabus', 'course_id', '1:1');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (8, 'course', 'id', 'course_schedule', 'course_id', '1:N');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (9, 'course', 'id', 'student_course', 'course_id', '1:N');
INSERT INTO sys_table_relation (id, main_table, main_field, join_table, join_field, relation_type) VALUES (10, 'student_award', 'id', 'student_award_detail', 'award_id', '1:N');
